json.user_avatar		@user.avatar_file_name
json.user 				@user.full_name
json.email				@user.email
json.access_token		@user.access_token
json.created_at			@user.created_at
json.team				@user.team.name
json.company_subdomain	@user.account.subdomain
json.company_name		@user.account.company_name
json.company_url		@user.account.company_url
json.company_phone		@user.account.company_phone